version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: cafe_db
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: cook
      MYSQL_PASSWORD: meister10
      MYSQL_ROOT_PASSWORD: meister10
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - "3306:3306" # Optional, if you want to access MySQL from outside
  # WordPress service

  wordpress:
    image: wordpress:6.8.1
    restart: always
    container_name: cafe_wordpress
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: cook
      WORDPRESS_DB_PASSWORD: meister10
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./coffee-shop-theme:/var/www/html/wp-content/themes/coffee-shop-theme
      - ./wp_data:/var/www/html
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

volumes:
  db_data:
  wp_data: